### List all users
GET http://localhost:3001/users


### Create a new user
POST http://localhost:3001/users/signup
content-type: application/json

{
  "name": "TestForUserDTO1",
    "email": "testUserDTO@gmail.com",
    "password": "DTP12345",
    "right": "Write"
}

### Get a particular user
GET http://localhost:3001/users/6


### DELETE a particular user!
DELETE  http://localhost:3001/users/2


//PRODUCTS
### List all products
GET http://localhost:3001/products


### Create a new product
POST http://localhost:3001/products
content-type: application/json

{
    "name": "BuggUniqueMigration",
    "unit": "tons",
    "quantity": 2,

}

### Get a particular user
GET http://localhost:3001/products/7


### DELETE a particular product!
DELETE  http://localhost:3001/products/4


### WAREHOUSES
GET http://localhost:3001/warehouses

### Create a new Warehouse
POST http://localhost:3001/warehouses
content-type: application/json

{
    "name": "TestCreateWarehouse2",
    "location": "Belgum",
    "storage": 100000,
    "hazardous": false
}