### List all users
GET http://localhost:3001/users


### Create a new user
POST http://localhost:3001/users
content-type: application/json

{
  "name": "Test3",
  "email": "test3@gmail.com",
  "password": "somePass",
  "rights": "Write"
}


### Get a particular user
GET http://localhost:3001/users/4