### List all users
GET http://localhost:3001/users


### Create a new user
POST http://localhost:3001/auth/signup
content-type: application/json

{
  "name": "TestFrontEndUser",
    "email": "TestFrontEndUser@gmail.com",
    "password": "reactJS12345",
    "right": "Read"
}

### Get a particular user
GET http://localhost:3001/users/6


### DELETE a particular user!
DELETE  http://localhost:3001/users/2


//PRODUCTS
### List all products
GET http://localhost:3001/products


### Create a new product
POST http://localhost:3001/products
content-type: application/json

{
    "name": "NPK",
    "unit": "t",
    "quantity": 2,

}

### Get a particular user
GET http://localhost:3001/products/7


### DELETE a particular product!
DELETE  http://localhost:3001/products/4


### WAREHOUSES
GET http://localhost:3001/warehouses

### Create a new Warehouse
POST http://localhost:3001/warehouses
content-type: application/json

{
    "name": "US-Warehouse",
    "location": "USA",
    "storage": 10000000,
    "hazardous": false
}

### Edit a new Warehouse
PUT http://localhost:3001/warehouses/1
content-type: application/json

{
    "name": "WarehouseBGTest1",
    "location": "Bulgaria",
    "storage": 333,
    "hazardous": false
}

###
GET http://localhost:3001/movements
